---
name: flask app build and deployment
on:
  push:
    branches:
    - main
    paths:
    - 'apps/**'
jobs:
  dev:
    name: Flask app deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ['apps']
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.folder }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # - name: docker login
      #   run: |
      #     echo ${{ secrets.DOCKER_TOKEN }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
      - name: docker build 
        run: |
          docker build -t  ${{ secrets.DOCKER_USER }}/flaskapi:$GITHUB_RUN_ID .
      - name: show the docker image name
        run: |
          echo ${{ secrets.DOCKER_USER }}/flaskapi:$GITHUB_RUN_ID
      - name: docker push 
        run: |
          docker push ${{ secrets.DOCKER_USER }}/flaskapi:$GITHUB_RUN_ID
      - name: docker logout
        run: |
          docker logout
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          # directory: ./
          key: ${{secrets.SSH_KEY}}
          inventory: |
            [all]
            18.234.81.146