---
name: infra provisioning
on:
  push:
    branches:
    - main
    paths:
    - 'infra-code/**'
jobs:
  dev:
    name: terraform deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ['infra-code']
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.folder }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: version
        run: |
          echo "terraform provison area"