---
name: machine learning model deployment
on: [push]
jobs:
  dev:
    name: dev recommendation
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: docker login
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
      - name: docker build 
        run: |
          docker build -t  ${{ secrets.DOCKER_USER }}/flaskapi:$GITHUB_RUN_ID .
      - name: show the docker image name
        run: |
           image=`${{ secrets.DOCKER_USER }}/flaskapi:$GITHUB_RUN_ID`
           echo $image
      - name: docker push 
        run: |
          docker push ${{ secrets.DOCKER_USER }}/flaskapi:$GITHUB_RUN_ID
      - name: docker logout
        run: |
          docker logout
